test_homepage:
    path:     /
    defaults: { _controller: TestBundle:Default:index }
liste_contacts:
    path:     /listecontacts
    defaults: { _controller: TestBundle:Default:listecontacts }
delete_contact:
    path:     /deletecontact
    defaults: { _controller: TestBundle:Default:deletecontact }
creer_contact:
    path:     /creercontact
    defaults: { _controller: TestBundle:Default:creercontact }
ajouter_carnet:
    path:     /ajouteraucarnet
    defaults: { _controller: TestBundle:Default:addcontactcarnet }
edit_contact:
    path:     /editcontact
    defaults: { _controller: TestBundle:Default:editcontact}